### PR TITLE
Added strikethrough feature for completed TODOs

### PR DESCRIPTION
**Pull request by Hemant-Lohar**
Now after  Completion, only completed  TODOs will have a StrikeThrough line over text.

### CODE REVIEW

**Comment by Gourav2609** [comment]
I see that the strike text in appearing not just in ALL section but also in COMPLETED section.....correct it

**Comment by Hemant-Lohar** [comment]
Okay I'll do

**Comment by Hemant-Lohar** [comment]
now check for it completed

**Comment by Gourav2609** [comment]
Good work @Hemant-Lohar

**Review by Gourav2609 — APPROVED** [review]
done

**Comment by Hemant-Lohar** [comment]
> done

Thank you @Gourav2609 . Change the Topic of Repository from hactoberfest  to ===> hacktoberfest.  that K is missing

**Pull request merged**
